services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: hotel-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    command: npm run dev   

  chat:
    build:
      context: .
      dockerfile: Dockerfile.chat
    container_name: hotel-chat
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    command: node chatServer.js
